version: '3'
services:
  database:
    image: 'mysql/mysql-server:latest'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: 'database'
      MYSQL_DATABASE: 'wordpress_db'
      MYSQL_USER: 'wp_user'
      MYSQL_PASSWORD: 'wp_password'
    volumes:
      - wordpress_database:/var/lib/mysql
    restart: always
    networks:
      - wordpress

  wordpress-server:
    depends_on: 
      - database
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: wordpress-local/server
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'database:3306'
      WORDPRESS_DB_USER: 'wp_user'
      WORDPRESS_DB_PASSWORD: 'wp_password'
      WORDPRESS_DB_NAME: 'wordpress_db'
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge

volumes:
  wordpress_database:
    driver: local
